import styles from '@/styles/index.module.scss'
import { type Article, type WikiData } from '@/types'
import { formatArticleTitle, getFormattedDate } from '@/utils'
import Head from 'next/head'
import { useEffect, useState } from 'react'

const Results = ({ articles }: { articles: Article[] | null }) => {
  return (
    <div className={styles.resultsContainer}>
      <div>
        {articles?.map(({ article }) => (
          <p key={article}>{formatArticleTitle(article)}</p>
        ))}
      </div>
    </div>
  )
}

const ActionBar = () => {
  return <div className={styles.actionContainer}>Action Bar</div>
}

export default function Home() {
  const yesterdayDate = new Date(new Date().setDate(new Date().getDate() - 1))
  const { year, month, day } = getFormattedDate(yesterdayDate)
  const [limit, setLimit] = useState(100)

  const [data, setData] = useState<Article[] | null>(null)
  useEffect(() => {
    fetch(
      `https://wikimedia.org/api/rest_v1/metrics/pageviews/top/en.wikipedia/all-access/${year}/${month}/${day}`
    )
      .then(res => {
        if (res.ok) {
          return res.json()
        }
        throw res
      })
      .then((wikiData: WikiData) => {
        if (wikiData?.items[0]) {
          setData(wikiData.items[0].articles.slice(0, limit))
        }
      })
      .catch(err => {
        console.error(err)
      })
  }, [])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.header} />

        <h1 className={styles.title}>Top Wikipedia Articles</h1>

        <ActionBar />

        <Results articles={data} />
      </main>
    </>
  )
}
